version: "3.1"
services:
  downloader:
    build: "downloader"
    volumes:
      - ".:/home/downloader/rpmbuild"
    working_dir: "/home/downloader/rpmbuild"
    command: "spectool -g -R SPECS/freeform-nd.spec"
